//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
[System.Xml.Serialization.XmlRootAttribute("Hypermedia", Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd", IsNullable=false)]
public partial class HypermediaType {
    
    private ParameterType[] transferParametersField;
    
    private DocumentType[] documentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Parameters", IsNullable=false)]
    public ParameterType[] TransferParameters {
        get {
            return this.transferParametersField;
        }
        set {
            this.transferParametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable=false)]
    public DocumentType[] Documents {
        get {
            return this.documentsField;
        }
        set {
            this.documentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class ParameterType {
    
    private PropertyType[] propertyField;
    
    private string typeNameField;
    
    private bool usedForQueriesField;
    
    private bool usedForActionsField;
    
    private string parentTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property")]
    public PropertyType[] Property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string typeName {
        get {
            return this.typeNameField;
        }
        set {
            this.typeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool usedForQueries {
        get {
            return this.usedForQueriesField;
        }
        set {
            this.usedForQueriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool usedForActions {
        get {
            return this.usedForActionsField;
        }
        set {
            this.usedForActionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string parentType {
        get {
            return this.parentTypeField;
        }
        set {
            this.parentTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class PropertyType {
    
    private string nameField;
    
    private string typeField;
    
    private bool mandatoryField;
    
    private bool mandatoryFieldSpecified;
    
    private bool isKeyField;
    
    private bool isKeyFieldSpecified;
    
    private bool hiddenField;
    
    private bool hiddenFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool mandatory {
        get {
            return this.mandatoryField;
        }
        set {
            this.mandatoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mandatorySpecified {
        get {
            return this.mandatoryFieldSpecified;
        }
        set {
            this.mandatoryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isKey {
        get {
            return this.isKeyField;
        }
        set {
            this.isKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isKeySpecified {
        get {
            return this.isKeyFieldSpecified;
        }
        set {
            this.isKeyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool hidden {
        get {
            return this.hiddenField;
        }
        set {
            this.hiddenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hiddenSpecified {
        get {
            return this.hiddenFieldSpecified;
        }
        set {
            this.hiddenFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class ResultDocumentType {
    
    private string documentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class QueryParameterType {
    
    private string parameterNameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parameterName {
        get {
            return this.parameterNameField;
        }
        set {
            this.parameterNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class LinkType {
    
    private QueryParameterType[] queryParametersField;
    
    private ResultDocumentType[] resultDocumentsField;
    
    private string relField;
    
    private string documentField;
    
    private string queryField;
    
    private string contentTypeField;
    
    private string parameterTypeNameField;
    
    private bool mandatoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("QueryParameter", IsNullable=false)]
    public QueryParameterType[] QueryParameters {
        get {
            return this.queryParametersField;
        }
        set {
            this.queryParametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ResultDocument", IsNullable=false)]
    public ResultDocumentType[] ResultDocuments {
        get {
            return this.resultDocumentsField;
        }
        set {
            this.resultDocumentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rel {
        get {
            return this.relField;
        }
        set {
            this.relField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contentType {
        get {
            return this.contentTypeField;
        }
        set {
            this.contentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parameterTypeName {
        get {
            return this.parameterTypeNameField;
        }
        set {
            this.parameterTypeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool mandatory {
        get {
            return this.mandatoryField;
        }
        set {
            this.mandatoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class PermissionType {
    
    private string scopeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scope {
        get {
            return this.scopeField;
        }
        set {
            this.scopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class PermissionsType {
    
    private PermissionType[] permissionField;
    
    private bool authorizeField;
    
    public PermissionsType() {
        this.authorizeField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Permission")]
    public PermissionType[] Permission {
        get {
            return this.permissionField;
        }
        set {
            this.permissionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool authorize {
        get {
            return this.authorizeField;
        }
        set {
            this.authorizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class PoliciesType {
    
    private PermissionsType permissionsField;
    
    /// <remarks/>
    public PermissionsType Permissions {
        get {
            return this.permissionsField;
        }
        set {
            this.permissionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class OperationType {
    
    private PoliciesType policiesField;
    
    private string nameField;
    
    private method methodField;
    
    private string titleField;
    
    private string parameterTypeNameField;
    
    private string resultDocumentField;
    
    /// <remarks/>
    public PoliciesType Policies {
        get {
            return this.policiesField;
        }
        set {
            this.policiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public method method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parameterTypeName {
        get {
            return this.parameterTypeNameField;
        }
        set {
            this.parameterTypeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resultDocument {
        get {
            return this.resultDocumentField;
        }
        set {
            this.resultDocumentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public enum method {
    
    /// <remarks/>
    Post,
    
    /// <remarks/>
    Delete,
    
    /// <remarks/>
    Patch,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class EntityType {
    
    private string collectionNameField;
    
    private string documentField;
    
    private string referencedDocumentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string collectionName {
        get {
            return this.collectionNameField;
        }
        set {
            this.collectionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string referencedDocument {
        get {
            return this.referencedDocumentField;
        }
        set {
            this.referencedDocumentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class ClassificationType {
    
    private string classField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.bluehands.de/2022/Hypermedia.xsd")]
public partial class DocumentType {
    
    private ClassificationType[] classificationsField;
    
    private PropertyType[] propertiesField;
    
    private EntityType[] entitiesField;
    
    private OperationType[] operationsField;
    
    private LinkType[] linksField;
    
    private PoliciesType policiesField;
    
    private string nameField;
    
    private string titleField;
    
    private bool isQueryResultField;
    
    private bool isQueryResultFieldSpecified;
    
    private bool hasSelfLinkField;
    
    private string parentDocumentField;
    
    public DocumentType() {
        this.hasSelfLinkField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Classification", IsNullable=false)]
    public ClassificationType[] Classifications {
        get {
            return this.classificationsField;
        }
        set {
            this.classificationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
    public PropertyType[] Properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Entity", IsNullable=false)]
    public EntityType[] Entities {
        get {
            return this.entitiesField;
        }
        set {
            this.entitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Operation", IsNullable=false)]
    public OperationType[] Operations {
        get {
            return this.operationsField;
        }
        set {
            this.operationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Link", IsNullable=false)]
    public LinkType[] Links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
    
    /// <remarks/>
    public PoliciesType Policies {
        get {
            return this.policiesField;
        }
        set {
            this.policiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isQueryResult {
        get {
            return this.isQueryResultField;
        }
        set {
            this.isQueryResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isQueryResultSpecified {
        get {
            return this.isQueryResultFieldSpecified;
        }
        set {
            this.isQueryResultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool hasSelfLink {
        get {
            return this.hasSelfLinkField;
        }
        set {
            this.hasSelfLinkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string parentDocument {
        get {
            return this.parentDocumentField;
        }
        set {
            this.parentDocumentField = value;
        }
    }
}
