namespace RESTyard.HtoSourceGenerators;

/// <summary>
/// Emits the <c>{ClassName}Properties</c> POCO class for an HTO:
/// data properties only, with non-RESTyard attributes forwarded
/// and XML doc comments copied verbatim.
/// </summary>
internal static class PropertiesPocoEmitter
{
    internal static string GeneratePropertiesPoco(HtoMetadata metadata)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();

        if (!string.IsNullOrEmpty(metadata.Namespace))
        {
            w.Line($"namespace {metadata.Namespace};");
            w.Line();
        }

        w.Line($"public class {metadata.ClassName}Properties");
        using (w.Block())
        {
            foreach (var prop in metadata.Properties)
            {
                if (prop.XmlDocComment != null)
                {
                    w.Lines(prop.XmlDocComment);
                }

                foreach (var attr in prop.ForwardedAttributes)
                {
                    w.Line(attr);
                }

                w.Line($"public {prop.TypeFullName} {EmitHelpers.EscapeIdentifier(prop.Name)} {{ get; set; }} = default!;");
            }
        }

        return w.ToString();
    }
}
