using System.Collections.Immutable;
using static RESTyard.HtoSourceGenerators.EmitHelpers;

namespace RESTyard.HtoSourceGenerators;

/// <summary>
/// Emits the per-assembly schema registry (with its discovery assembly attribute)
/// and the action-result registry for multi-assembly support.
/// </summary>
internal static class RegistryEmitter
{
    /// <summary>
    /// Generates a per-assembly schema registry class and assembly attribute.
    /// </summary>
    internal static string GenerateRegistrySource(
        ImmutableArray<HtoMetadata> allHtos,
        string assemblyNameSafe)
    {
        var registryClassName = SchemaTypeNames.HypermediaSchemaRegistryPrefix + assemblyNameSafe;

        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();
        w.Line($"using {SchemaTypeNames.SchemaModelNamespace};");
        w.Line($"using {SchemaTypeNames.JsonSchemaFactoryNamespace};");
        w.Line();

        // Assembly attribute for runtime discovery
        w.Line($"[assembly: global::RESTyard.Schema.Model.HypermediaSchemaRegistryAttribute(typeof({registryClassName}))]");
        w.Line();

        w.Line($"public static class {registryClassName}");
        using (w.Block())
        {
            w.Line($"public static System.Collections.Generic.IReadOnlyList<{SchemaTypeNames.EntityTypeSchema}> GetSchemas({SchemaTypeNames.IJsonSchemaFactory} schemaFactory)");
            using (w.Block())
            {
                w.Line($"return new {SchemaTypeNames.EntityTypeSchema}[]");
                using (w.Block(close: "};"))
                {
                    foreach (var hto in allHtos)
                    {
                        var fullMapperName = string.IsNullOrEmpty(hto.Namespace)
                            ? $"{hto.ClassName}Schema"
                            : $"global::{hto.Namespace}.{hto.ClassName}Schema";

                        w.Line(hto.NeedsSchemaFactory
                            ? $"{fullMapperName}.GetSchema(schemaFactory),"
                            : $"{fullMapperName}.GetSchema(),");
                    }
                }
            }
        }

        return w.ToString();
    }

    /// <summary>
    /// Generates an action result registry for multi-assembly support.
    /// Emits a static class with action-to-result mappings that <c>HypermediaSchemaBuilder</c>
    /// can discover and merge into the schema.
    /// </summary>
    internal static string GenerateActionResultRegistrySource(
        ImmutableDictionary<(string HtoClassName, string ActionPropertyName), (string ResultSchemaName, ImmutableArray<string> ResultClasses)> mappings,
        string assemblyNameSafe)
    {
        var registryClassName = "HypermediaActionResultRegistry_" + assemblyNameSafe;

        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();
        w.Line($"using {SchemaTypeNames.SchemaModelNamespace};");
        w.Line();

        w.Line($"public static class {registryClassName}");
        using (w.Block())
        {
            w.Line("public static System.Collections.Generic.IReadOnlyList<ActionResultMapping> GetMappings()");
            using (w.Block())
            {
                w.Line("return new ActionResultMapping[]");
                using (w.Block(close: "};"))
                {
                    foreach (var kvp in mappings)
                    {
                        w.Line($"new ActionResultMapping {{ EntityName = \"{EscapeString(kvp.Key.HtoClassName)}\", ActionName = \"{EscapeString(kvp.Key.ActionPropertyName)}\", ResultName = \"{EscapeString(kvp.Value.ResultSchemaName)}\", ResultClasses = new[] {{ {QuotedList(kvp.Value.ResultClasses)} }} }},");
                    }
                }
            }
        }

        return w.ToString();
    }
}
