using static RESTyard.HtoSourceGenerators.EmitHelpers;

namespace RESTyard.HtoSourceGenerators;

/// <summary>
/// Emits the per-HTO <c>{ClassName}Schema.GetSchema()</c> source producing an
/// <c>EntityTypeSchema</c> instance. Pure <see cref="HtoMetadata"/> → string function.
/// </summary>
internal static class SchemaEmitter
{
    internal static string GenerateSchemaSource(HtoMetadata metadata)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();
        w.Line($"using {SchemaTypeNames.SchemaModelNamespace};");

        if (metadata.NeedsSchemaFactory)
        {
            w.Line($"using {SchemaTypeNames.JsonSchemaFactoryNamespace};");
            w.Line($"using {SchemaTypeNames.JsonSchemaNamespace};");
            w.Line($"using {SchemaTypeNames.JsonDocumentNamespace};");
        }

        w.Line();

        if (!string.IsNullOrEmpty(metadata.Namespace))
        {
            w.Line($"namespace {metadata.Namespace};");
            w.Line();
        }

        w.Line($"public static class {metadata.ClassName}Schema");
        using (w.Block())
        {
            // GetSchema() accepts IJsonSchemaFactory when there are properties or parameterized actions
            w.Line(metadata.NeedsSchemaFactory
                ? $"public static {SchemaTypeNames.EntityTypeSchema} GetSchema({SchemaTypeNames.IJsonSchemaFactory} schemaFactory)"
                : $"public static {SchemaTypeNames.EntityTypeSchema} GetSchema()");
            using (w.Block())
            {
                if (metadata.Properties.Length > 0)
                {
                    // Properties schema is generated via the generated POCO type
                    w.Line($"var propertiesSchema = schemaFactory.Generate(typeof({metadata.ClassName}Properties));");
                    w.Line();
                }

                w.Line($"return new {SchemaTypeNames.EntityTypeSchema}");
                using (w.Block(close: "};"))
                {
                    w.Line($"{SchemaTypeNames.EntityTypeSchema_Name} = \"{EscapeString(metadata.SchemaName)}\",");

                    if (metadata.Title != null)
                    {
                        w.Line($"{SchemaTypeNames.EntityTypeSchema_Title} = \"{EscapeString(metadata.Title)}\",");
                    }

                    if (metadata.Description != null)
                    {
                        w.Line($"{SchemaTypeNames.EntityTypeSchema_Description} = \"{EscapeString(metadata.Description)}\",");
                    }

                    if (metadata.IsDeprecated)
                    {
                        w.Line($"{SchemaTypeNames.EntityTypeSchema_IsDeprecated} = true,");
                        if (metadata.DeprecationMessage != null)
                        {
                            w.Line($"{SchemaTypeNames.EntityTypeSchema_DeprecationMessage} = \"{EscapeString(metadata.DeprecationMessage)}\",");
                        }
                    }

                    EmitAccessGroups(w, metadata.AccessGroups, SchemaTypeNames.EntityTypeSchema_AccessGroups);

                    w.Line($"{SchemaTypeNames.EntityTypeSchema_Classes} = new[] {{ {QuotedList(metadata.Classes)} }},");

                    if (metadata.Properties.Length > 0)
                    {
                        w.Line($"{SchemaTypeNames.EntityTypeSchema_PropertiesSchema} = propertiesSchema,");
                    }

                    if (metadata.Links.Length > 0)
                    {
                        EmitLinksArray(w, metadata.Links);
                    }

                    if (metadata.Actions.Length > 0)
                    {
                        EmitActionsArray(w, metadata.Actions);
                    }

                    if (metadata.EmbeddedEntities.Length > 0)
                    {
                        EmitEmbeddedEntitiesArray(w, metadata.EmbeddedEntities);
                    }
                }
            }
        }

        return w.ToString();
    }

    private static void EmitLinksArray(CodeWriter w, EquatableArray<LinkMetadata> links)
    {
        w.Line($"{SchemaTypeNames.EntityTypeSchema_Links} = new {SchemaTypeNames.LinkDescription}[]");
        using (w.Block(close: "},"))
        {
            foreach (var link in links)
            {
                w.Line($"new {SchemaTypeNames.LinkDescription}");
                using (w.Block(close: "},"))
                {
                    w.Line($"{SchemaTypeNames.LinkDescription_Relations} = new[] {{ {QuotedList(link.Relations)} }},");
                    w.Line($"{SchemaTypeNames.LinkDescription_TargetName} = \"{EscapeString(link.TargetSchemaName)}\",");
                    w.Line($"{SchemaTypeNames.LinkDescription_TargetClasses} = new[] {{ {QuotedList(link.TargetClasses)} }},");

                    if (link.Title != null)
                    {
                        w.Line($"{SchemaTypeNames.LinkDescription_Title} = \"{EscapeString(link.Title)}\",");
                    }

                    if (link.Description != null)
                    {
                        w.Line($"{SchemaTypeNames.LinkDescription_Description} = \"{EscapeString(link.Description)}\",");
                    }

                    if (link.IsDeprecated)
                    {
                        w.Line($"{SchemaTypeNames.LinkDescription_IsDeprecated} = true,");
                        if (link.DeprecationMessage != null)
                        {
                            w.Line($"{SchemaTypeNames.LinkDescription_DeprecationMessage} = \"{EscapeString(link.DeprecationMessage)}\",");
                        }
                    }

                    EmitAccessGroups(w, link.AccessGroups, SchemaTypeNames.LinkDescription_AccessGroups);
                    w.Line($"{SchemaTypeNames.LinkDescription_IsMandatory} = {(link.IsMandatory ? "true" : "false")},");
                }
            }
        }
    }

    private static void EmitActionsArray(CodeWriter w, EquatableArray<ActionMetadata> actions)
    {
        w.Line($"{SchemaTypeNames.EntityTypeSchema_Actions} = new {SchemaTypeNames.ActionDescription}[]");
        using (w.Block(close: "},"))
        {
            foreach (var action in actions)
            {
                w.Line($"new {SchemaTypeNames.ActionDescription}");
                using (w.Block(close: "},"))
                {
                    w.Line($"{SchemaTypeNames.ActionDescription_Name} = \"{EscapeString(action.Name)}\",");

                    if (action.Title != null)
                    {
                        w.Line($"{SchemaTypeNames.ActionDescription_Title} = \"{EscapeString(action.Title)}\",");
                    }

                    if (action.Description != null)
                    {
                        w.Line($"{SchemaTypeNames.ActionDescription_Description} = \"{EscapeString(action.Description)}\",");
                    }

                    if (action.IsFileUpload)
                    {
                        w.Line($"{SchemaTypeNames.ActionDescription_ContentType} = \"multipart/form-data\",");
                        w.Line($"{SchemaTypeNames.ActionDescription_IsFileUpload} = true,");
                    }

                    if (action.ParameterTypeFullName != null)
                    {
                        w.Line($"{SchemaTypeNames.ActionDescription_ParameterSchema} = schemaFactory.Generate(typeof({action.ParameterTypeFullName})),");
                    }

                    if (action.IsDeprecated)
                    {
                        w.Line($"{SchemaTypeNames.ActionDescription_IsDeprecated} = true,");
                        if (action.DeprecationMessage != null)
                        {
                            w.Line($"{SchemaTypeNames.ActionDescription_DeprecationMessage} = \"{EscapeString(action.DeprecationMessage)}\",");
                        }
                    }

                    if (action.ResultSchemaName != null)
                    {
                        w.Line($"{SchemaTypeNames.ActionDescription_ResultName} = \"{EscapeString(action.ResultSchemaName)}\",");

                        if (action.ResultClasses is { Length: > 0 } rc)
                        {
                            w.Line($"{SchemaTypeNames.ActionDescription_ResultClasses} = new[] {{ {QuotedList(rc)} }},");
                        }
                    }

                    EmitAccessGroups(w, action.AccessGroups, SchemaTypeNames.ActionDescription_AccessGroups);
                    w.Line($"{SchemaTypeNames.ActionDescription_IsMandatory} = {(action.IsMandatory ? "true" : "false")},");
                }
            }
        }
    }

    private static void EmitEmbeddedEntitiesArray(CodeWriter w, EquatableArray<EmbeddedEntityMetadata> embeddedEntities)
    {
        w.Line($"{SchemaTypeNames.EntityTypeSchema_EmbeddedEntities} = new {SchemaTypeNames.EmbeddedEntityDescription}[]");
        using (w.Block(close: "},"))
        {
            foreach (var embedded in embeddedEntities)
            {
                w.Line($"new {SchemaTypeNames.EmbeddedEntityDescription}");
                using (w.Block(close: "},"))
                {
                    w.Line($"{SchemaTypeNames.EmbeddedEntityDescription_Relations} = new[] {{ {QuotedList(embedded.Relations)} }},");
                    w.Line($"{SchemaTypeNames.EmbeddedEntityDescription_TargetName} = \"{EscapeString(embedded.TargetSchemaName)}\",");
                    w.Line($"{SchemaTypeNames.EmbeddedEntityDescription_TargetClasses} = new[] {{ {QuotedList(embedded.TargetClasses)} }},");
                    w.Line($"{SchemaTypeNames.EmbeddedEntityDescription_IsCollection} = {(embedded.IsCollection ? "true" : "false")},");

                    if (embedded.Title != null)
                    {
                        w.Line($"{SchemaTypeNames.EmbeddedEntityDescription_Title} = \"{EscapeString(embedded.Title)}\",");
                    }

                    if (embedded.Description != null)
                    {
                        w.Line($"{SchemaTypeNames.EmbeddedEntityDescription_Description} = \"{EscapeString(embedded.Description)}\",");
                    }

                    if (embedded.IsDeprecated)
                    {
                        w.Line($"{SchemaTypeNames.EmbeddedEntityDescription_IsDeprecated} = true,");
                        if (embedded.DeprecationMessage != null)
                        {
                            w.Line($"{SchemaTypeNames.EmbeddedEntityDescription_DeprecationMessage} = \"{EscapeString(embedded.DeprecationMessage)}\",");
                        }
                    }

                    EmitAccessGroups(w, embedded.AccessGroups, SchemaTypeNames.EmbeddedEntityDescription_AccessGroups);
                    w.Line($"{SchemaTypeNames.EmbeddedEntityDescription_IsMandatory} = {(embedded.IsMandatory ? "true" : "false")},");
                }
            }
        }
    }

    /// <summary>
    /// Emits a <c>AccessGroups = new[] { "group1", "group2" }</c> assignment
    /// when the access groups array is non-empty. Emits nothing when empty (null in schema = public).
    /// </summary>
    private static void EmitAccessGroups(CodeWriter w, EquatableArray<string> accessGroups, string propertyName)
    {
        if (accessGroups.Length == 0)
        {
            return;
        }

        w.Line($"{propertyName} = new[] {{ {QuotedList(accessGroups)} }},");
    }
}
