namespace RESTyard.HtoSourceGenerators;

/// <summary>
/// Emits the shared, fully static <c>SirenHelper</c> class (AddLink, AddAction, BuildParameterField)
/// used by all per-HTO SirenExtensions classes. Emitted once per assembly when Siren = true.
/// </summary>
internal static class SirenHelperEmitter
{
    internal static string GenerateSirenHelper() => Source;

    private static readonly string Source =
$$"""
// <auto-generated/>
#nullable enable

using {{SchemaTypeNames.SirenModelNamespace}};
using {{SchemaTypeNames.RouteResolverNamespace}};
using {{SchemaTypeNames.QueryNamespace}};
using System.Collections.Generic;
using System.Linq;
using RESTyard.AspNetCore.Hypermedia;

internal static class SirenHelper
{
    internal static void AddLink(
        IList<SirenLink> links,
        ILink? link,
        string[] rel,
        string propertyName,
        IHypermediaRouteResolver resolver,
        IQueryStringBuilder queryStringBuilder)
    {
        if (link is null)
        {
            throw new System.InvalidOperationException(
                $"Non-nullable link property '{propertyName}' is null. " +
                "Ensure the property is initialized or marked as nullable.");
        }

        var route = resolver.ReferenceToRoute(link.Reference);
        var query = link.Reference.GetQuery();
        var href = route.Url + queryStringBuilder.CreateQueryString(query);
        links.Add(new SirenLink
        {
            Rel = rel,
            Href = href,
            Type = route.AvailableMediaTypes.Count > 0
                ? string.Join(",", route.AvailableMediaTypes)
                : null,
        });
    }

    internal static void AddAction(
        IList<SirenAction> actions,
        RESTyard.AspNetCore.Hypermedia.IHypermediaObject hto,
        RESTyard.AspNetCore.Hypermedia.Actions.HypermediaActionBase action,
        string actionName,
        string? actionTitle,
        string[] userClasses,
        IHypermediaRouteResolver resolver)
    {
        ResolvedRoute resolvedRoute;
        if (action is RESTyard.AspNetCore.Hypermedia.Actions.HypermediaExternalActionBase externalAction)
        {
            resolvedRoute = new ResolvedRoute(
                externalAction.ExternalUri.ToString(),
                externalAction.HttpMethod,
                acceptableMediaType: externalAction.AcceptedMediaType);
        }
        else
        {
            resolvedRoute = resolver.ActionToRoute(hto, action);
        }

        string classField;
        string? actionType = null;
        var fields = new List<SirenField>();

        if (action is RESTyard.AspNetCore.Hypermedia.Actions.IFileUploadConfiguration fileUploadConfig)
        {
            actionType = resolvedRoute.AcceptableMediaType ?? RESTyard.MediaTypes.DefaultMediaTypes.MultipartFormData;
            var uploadConfig = fileUploadConfig.FileUploadConfiguration;
            var fileField = new SirenField { Name = "UploadFiles", Type = "file" };
            if (uploadConfig.Accept.Any())
            {
                fileField.Accept = string.Join(",", uploadConfig.Accept);
            }
            if (uploadConfig.MaxFileSizeBytes >= 0)
            {
                fileField.MaxFileSizeBytes = uploadConfig.MaxFileSizeBytes;
            }
            if (uploadConfig.AllowMultiple)
            {
                fileField.AllowMultiple = true;
            }
            fields.Add(fileField);

            if (action.TryGetParameterType(out var paramType))
            {
                classField = RESTyard.AspNetCore.WebApi.Formatter.ActionClasses.FileUploadActionWithParameterClass;
                fields.Add(BuildParameterField(action, paramType, resolver));
            }
            else
            {
                classField = RESTyard.AspNetCore.WebApi.Formatter.ActionClasses.FileUploadActionClass;
            }
        }
        else if (action.TryGetParameterType(out var paramType))
        {
            actionType = resolvedRoute.AcceptableMediaType ?? RESTyard.MediaTypes.DefaultMediaTypes.ApplicationJson;
            classField = RESTyard.AspNetCore.WebApi.Formatter.ActionClasses.ParameterActionClass;
            fields.Add(BuildParameterField(action, paramType, resolver));
        }
        else
        {
            classField = RESTyard.AspNetCore.WebApi.Formatter.ActionClasses.ParameterLessActionClass;
        }

        var classList = new List<string>();
        classList.AddRange(userClasses);
        classList.Add(classField);

        actions.Add(new SirenAction
        {
            Name = actionName,
            Href = resolvedRoute.Url,
            Method = resolvedRoute.HttpMethod ?? "Undefined",
            Title = actionTitle,
            Class = classList,
            Type = actionType,
            Fields = fields.Count > 0 ? fields : null,
        });
    }

    private static SirenField BuildParameterField(
        RESTyard.AspNetCore.Hypermedia.Actions.HypermediaActionBase action,
        System.Type parameterType,
        IHypermediaRouteResolver resolver)
    {
        var paramName = RESTyard.AspNetCore.Util.TypeExtension.BeautifulName(parameterType);
        var field = new SirenField
        {
            Name = paramName,
            Type = RESTyard.MediaTypes.DefaultMediaTypes.ApplicationJson,
        };

        object? routeKeys = action is RESTyard.AspNetCore.Hypermedia.IDynamicSchema dynamicSchema
            ? dynamicSchema.SchemaRouteKeys : null;
        resolver.TryGetRouteByType(parameterType, routeKeys).Match(
            some: classRoute => field.Class = new[] { classRoute.Url },
            none: () =>
            {
                var generatedUrl = resolver.RouteUrl(
                    "ActionParameterTypes",
                    new { parameterTypeName = paramName });
                generatedUrl.Match(
                    url => field.Class = new[] { url },
                    error => throw new System.InvalidOperationException(
                        $"No route found for action parameter type '{paramName}'. " +
                        $"Ensure 'AutoDeliverJsonSchemaForActionParameterTypes' is true in HypermediaExtensionsOptions, " +
                        $"or register a custom route for this type. Error: {error}"));
            });

        var prefilled = action.GetPrefilledParameter();
        if (prefilled is string str)
        {
            field.Value = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>(str);
        }
        else if (prefilled != null)
        {
            field.Value = prefilled;
        }

        return field;
    }

}

""";
}
