using System.Linq;
using static RESTyard.HtoSourceGenerators.EmitHelpers;

namespace RESTyard.HtoSourceGenerators;

/// <summary>
/// Emits per-HTO <c>ToSiren()</c> / <c>ToSirenEmbedded()</c> extension methods
/// plus the named Siren entity classes and the <c>OkSiren()</c> controller convenience extension.
/// Pure <see cref="HtoMetadata"/> → string function.
/// </summary>
internal static class SirenEmitter
{
    internal static string GenerateSirenSource(HtoMetadata metadata)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();
        w.Line($"using {SchemaTypeNames.SirenModelNamespace};");
        w.Line($"using {SchemaTypeNames.SirenNamespace};");
        w.Line($"using {SchemaTypeNames.RouteResolverNamespace};");
        w.Line($"using {SchemaTypeNames.QueryNamespace};");
        w.Line("using System.Collections.Generic;");
        w.Line("using System.Linq;");
        w.Line();

        if (!string.IsNullOrEmpty(metadata.Namespace))
        {
            w.Line($"namespace {metadata.Namespace};");
            w.Line();
        }

        var propertiesType = metadata.Properties.Length > 0
            ? metadata.ClassName + "Properties"
            : SchemaTypeNames.NoProperties;
        var sirenClassName = metadata.ClassName + "Siren";
        var sirenEmbeddedClassName = metadata.ClassName + "SirenEmbedded";

        // --- Named Siren classes (Step 6.9) ---
        // Empty derived classes give the generated POCOs a stable, HTO-specific type name
        // (better OpenAPI/Swagger output and clearer IDE tooltips than SirenEntity<T>).
        w.Line($"/// <summary>Named Siren root entity for <see cref=\"{metadata.ClassName}\"/>. Returned by <c>ToSiren()</c>.</summary>");
        w.Line($"public sealed class {sirenClassName} : {SchemaTypeNames.SirenEntity}<{propertiesType}> {{ }}");
        w.Line();
        w.Line($"/// <summary>Named Siren embedded sub-entity for <see cref=\"{metadata.ClassName}\"/>. Returned by <c>ToSirenEmbedded()</c>; used internally when this HTO appears as an embedded entity.</summary>");
        w.Line($"public sealed class {sirenEmbeddedClassName} : {SchemaTypeNames.SirenEmbeddedEntity}<{propertiesType}> {{ }}");
        w.Line();

        w.Line($"public static class {metadata.ClassName}SirenExtensions");
        using (w.Block())
        {
            // --- ToSiren() ---
            EmitToSirenMethod(w, metadata, propertiesType, sirenClassName, sirenEmbeddedClassName, isEmbedded: false);

            w.Line();

            // --- OkSiren() controller convenience extension ---
            EmitOkSirenExtension(w, metadata, sirenClassName);

            w.Line();

            // --- ToSirenEmbedded() ---
            EmitToSirenMethod(w, metadata, propertiesType, sirenClassName, sirenEmbeddedClassName, isEmbedded: true);
        }

        return w.ToString();
    }

    /// <summary>
    /// Emits an OkSiren() controller extension that resolves services from HttpContext,
    /// calls ToSiren(), sets the Siren content type, and returns OkObjectResult.
    /// </summary>
    private static void EmitOkSirenExtension(CodeWriter w, HtoMetadata metadata, string sirenClassName)
    {
        var returnType = $"Microsoft.AspNetCore.Mvc.ActionResult<{sirenClassName}>";

        w.Line("/// <summary>");
        w.Line($"/// Converts the HTO to a <see cref=\"{sirenClassName}\"/> and returns an <see cref=\"Microsoft.AspNetCore.Mvc.ActionResult{{T}}\"/>");
        w.Line("/// with <c>application/vnd.siren+json</c> content type.");
        w.Line("/// Resolves route resolver, query string builder, and mapper options from DI.");
        w.Line("/// </summary>");
        w.Line($"public static {returnType} OkSiren(");
        using (w.Indent())
        {
            w.Line("this Microsoft.AspNetCore.Mvc.ControllerBase controller,");
            w.Line($"{metadata.ClassName} hto)");
        }

        using (w.Block())
        {
            w.Line("var services = controller.HttpContext.RequestServices;");
            w.Line("var resolver = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<RESTyard.AspNetCore.WebApi.RouteResolver.IHypermediaRouteResolver>(services);");
            w.Line("var queryStringBuilder = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<RESTyard.AspNetCore.Query.IQueryStringBuilder>(services);");
            w.Line($"var options = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<{SchemaTypeNames.SirenMapperOptions}>(services) ?? {SchemaTypeNames.SirenMapperOptions}.Default;");
            w.Line("controller.HttpContext.Response.ContentType = RESTyard.MediaTypes.DefaultMediaTypes.Siren;");
            w.Line("return hto.ToSiren(resolver, queryStringBuilder, options);");
        }
    }

    private static void EmitToSirenMethod(
        CodeWriter w,
        HtoMetadata metadata,
        string propertiesType,
        string sirenClassName,
        string sirenEmbeddedClassName,
        bool isEmbedded)
    {
        var returnType = isEmbedded ? sirenEmbeddedClassName : sirenClassName;
        var methodName = isEmbedded ? "ToSirenEmbedded" : "ToSiren";

        // EditorBrowsable(Never) for ToSirenEmbedded
        if (isEmbedded)
        {
            w.Line($"[{SchemaTypeNames.EditorBrowsableAttribute}({SchemaTypeNames.EditorBrowsableStateNever})]");
        }

        w.Line($"public static {returnType} {methodName}(");
        using (w.Indent())
        {
            w.Line($"this {metadata.ClassName} hto,");
            w.Line($"{SchemaTypeNames.IHypermediaRouteResolver} resolver,");
            w.Line($"{SchemaTypeNames.IQueryStringBuilder} queryStringBuilder,");
            w.Line($"{SchemaTypeNames.SirenMapperOptions}? options = null)");
        }

        using (w.Block())
        {
            // Resolve options — fall back to static default
            w.Line($"var effectiveOptions = options ?? {SchemaTypeNames.SirenMapperOptions}.Default;");
            w.Line();

            // Resolve self route
            w.Line("var selfRoute = resolver.ObjectToRoute(hto);");
            w.Line();

            // Create entity
            w.Line($"var entity = new {returnType}");
            using (w.Block(close: "};"))
            {
                // Rel — required on SirenEmbeddedEntity (via ISirenSubEntity), initialized empty for embedded (caller sets it)
                if (isEmbedded)
                {
                    w.Line("Rel = System.Array.Empty<string>(),");
                }

                EmitClassAssignment(w, metadata);

                if (metadata.Title != null)
                {
                    w.Line($"Title = \"{EscapeString(metadata.Title)}\",");
                }

                if (metadata.Properties.Length > 0)
                {
                    w.Line($"Properties = new {propertiesType}");
                    using (w.Block(close: "},"))
                    {
                        foreach (var prop in metadata.Properties)
                        {
                            w.Line($"{EscapeIdentifier(prop.Name)} = hto.{EscapeIdentifier(prop.OriginalName)},");
                        }
                    }
                }

                // Initialize collections
                w.Line($"Entities = new List<{SchemaTypeNames.ISirenSubEntity}>(),");
                w.Line($"Actions = new List<{SchemaTypeNames.SirenAction}>(),");
                w.Line($"Links = new List<{SchemaTypeNames.SirenLink}>(),");
            }

            w.Line();

            // Self link — skip if the HTO already has an explicit self link property
            var hasExplicitSelfLink = metadata.Links.Any(l =>
                l.Relations.Any(r => string.Equals(r, "self", System.StringComparison.OrdinalIgnoreCase)));
            if (!hasExplicitSelfLink)
            {
                w.Line("if (effectiveOptions.AutoSelfLink)");
                using (w.Block())
                {
                    w.Line($"entity.Links.Add(new {SchemaTypeNames.SirenLink} {{ Rel = new[] {{ \"self\" }}, Href = selfRoute.Url }});");
                }

                w.Line();
            }

            // Links — resolve URLs at runtime, append query string, deduplicate by relations
            EmitLinkResolution(w, metadata);

            // Actions — null-safe check, resolve route, build fields
            EmitActionResolution(w, metadata);
            // Embedded entities — resolved → inline, unresolved → linked sub-entity
            EmitEmbeddedEntityResolution(w, metadata);

            w.Line("return entity;");
        }
    }

    private static void EmitClassAssignment(CodeWriter w, HtoMetadata metadata)
    {
        if (metadata.Classes.Length > 0)
        {
            w.Line($"Class = new[] {{ {QuotedList(metadata.Classes)} }},");
        }
        else
        {
            // Fallback to type name when Classes is null (matches SirenConverter behavior)
            w.Line($"Class = new[] {{ \"{EscapeString(metadata.ClassName)}\" }},");
        }
    }

    private static void EmitLinkResolution(CodeWriter w, HtoMetadata metadata)
    {
        if (metadata.Links.Length == 0)
        {
            return;
        }

        foreach (var link in metadata.Links)
        {
            var relArray = StringArrayLiteral(link.Relations);
            // Media types from [HypermediaMediaType] — null when not declared
            // (AddLink then omits the link type unless the runtime sets one)
            var mediaTypesArray = link.MediaTypes.Length > 0
                ? StringArrayLiteral(link.MediaTypes)
                : "null";

            if (!link.IsMandatory)
            {
                w.Line($"if (hto.{EscapeIdentifier(link.PropertyName)} is {{ }} {link.PropertyName}Link)");
                using (w.Block())
                {
                    w.Line($"SirenHelper.AddLink(entity.Links, {link.PropertyName}Link, {relArray}, \"{EscapeString(link.PropertyName)}\", {mediaTypesArray}, resolver, queryStringBuilder, effectiveOptions);");
                }
            }
            else
            {
                w.Line($"SirenHelper.AddLink(entity.Links, hto.{EscapeIdentifier(link.PropertyName)}, {relArray}, \"{EscapeString(link.PropertyName)}\", {mediaTypesArray}, resolver, queryStringBuilder, effectiveOptions);");
            }

            w.Line();
        }
    }

    private static void EmitActionResolution(CodeWriter w, HtoMetadata metadata)
    {
        if (metadata.Actions.Length == 0)
        {
            return;
        }

        foreach (var action in metadata.Actions)
        {
            var classesArray = StringArrayLiteral(action.UserClasses);
            var title = action.Title != null ? $"\"{EscapeString(action.Title)}\"" : "null";

            if (action.IsMandatory)
            {
                // Mandatory action — always rendered; null or unavailable is a contract
                // violation and throws, consistent with links/embedded. Conditional
                // availability requires a nullable property.
                w.Line($"if (hto.{EscapeIdentifier(action.PropertyName)} is null)");
                using (w.Block())
                {
                    w.Line($"throw new System.InvalidOperationException(\"Mandatory action '{EscapeString(action.PropertyName)}' on '{EscapeString(metadata.ClassName)}' is null. Declare the property nullable if the action may be absent.\");");
                }

                w.Line($"if (!hto.{EscapeIdentifier(action.PropertyName)}.CanExecute())");
                using (w.Block())
                {
                    w.Line($"throw new System.InvalidOperationException(\"Mandatory action '{EscapeString(action.PropertyName)}' on '{EscapeString(metadata.ClassName)}' is not available (CanExecute() returned false). Declare the property nullable if the action may be absent.\");");
                }

                w.Line($"SirenHelper.AddAction(entity.Actions, hto, hto.{EscapeIdentifier(action.PropertyName)}, \"{EscapeString(action.Name)}\", {title}, {classesArray}, resolver);");
            }
            else
            {
                // Nullable action — null means "absent"; CanExecute() false also omits silently
                w.Line($"if (hto.{EscapeIdentifier(action.PropertyName)}?.CanExecute() == true)");
                using (w.Block())
                {
                    w.Line($"SirenHelper.AddAction(entity.Actions, hto, hto.{EscapeIdentifier(action.PropertyName)}, \"{EscapeString(action.Name)}\", {title}, {classesArray}, resolver);");
                }
            }

            w.Line();
        }
    }

    private static void EmitEmbeddedEntityResolution(CodeWriter w, HtoMetadata metadata)
    {
        if (metadata.EmbeddedEntities.Length == 0)
        {
            return;
        }

        foreach (var embedded in metadata.EmbeddedEntities)
        {
            var relArray = StringArrayLiteral(embedded.Relations);
            // Strip 'global::' prefix for cleaner generated code
            var targetFqn = embedded.TargetFullyQualifiedName;
            if (targetFqn.StartsWith("global::"))
            {
                targetFqn = targetFqn.Substring("global::".Length);
            }

            if (embedded.IsCollection)
            {
                EmitCollectionEmbeddedEntity(w, embedded, relArray, targetFqn, metadata.ClassName);
            }
            else
            {
                EmitSingleEmbeddedEntity(w, embedded, relArray, targetFqn, metadata.ClassName);
            }

            w.Line();
        }
    }

    private static void EmitSingleEmbeddedEntity(
        CodeWriter w, EmbeddedEntityMetadata embedded, string relArray, string targetFqn, string parentFqn)
    {
        if (!embedded.IsMandatory)
        {
            // Nullable single — skip when null
            w.Line($"if (hto.{EscapeIdentifier(embedded.PropertyName)} is {{ }} {embedded.PropertyName}Value)");
            using (w.Block())
            {
                EmitEmbeddedEntityBody(w, embedded.PropertyName + "Value", relArray, embedded, targetFqn);
            }
        }
        else
        {
            // Mandatory single — null guard
            w.Line($"if (hto.{EscapeIdentifier(embedded.PropertyName)} is null)");
            using (w.Block())
            {
                w.Line($"throw new System.InvalidOperationException(\"Mandatory embedded entity '{EscapeString(embedded.PropertyName)}' on '{EscapeString(parentFqn)}' is null.\");");
            }

            EmitEmbeddedEntityBody(w, "hto." + EscapeIdentifier(embedded.PropertyName), relArray, embedded, targetFqn);
        }
    }

    private static void EmitCollectionEmbeddedEntity(
        CodeWriter w, EmbeddedEntityMetadata embedded, string relArray, string targetFqn, string parentFqn)
    {
        if (!embedded.IsMandatory)
        {
            // Nullable collection — skip when null
            w.Line($"if (hto.{EscapeIdentifier(embedded.PropertyName)} is {{ }} {embedded.PropertyName}List)");
            using (w.Block())
            {
                w.Line($"foreach (var item in {embedded.PropertyName}List)");
                using (w.Block())
                {
                    EmitEmbeddedEntityBody(w, "item", relArray, embedded, targetFqn);
                }
            }
        }
        else
        {
            // Mandatory collection — null guard
            w.Line($"if (hto.{EscapeIdentifier(embedded.PropertyName)} is null)");
            using (w.Block())
            {
                w.Line($"throw new System.InvalidOperationException(\"Mandatory embedded entity '{EscapeString(embedded.PropertyName)}' on '{EscapeString(parentFqn)}' is null.\");");
            }

            w.Line($"foreach (var item in hto.{EscapeIdentifier(embedded.PropertyName)})");
            using (w.Block())
            {
                EmitEmbeddedEntityBody(w, "item", relArray, embedded, targetFqn);
            }
        }
    }

    /// <summary>
    /// Emits the body that processes a single embedded entity reference:
    /// resolved → call ToSirenEmbedded() on the instance,
    /// unresolved external → SirenLinkedEntity with URI,
    /// unresolved internal → SirenLinkedEntity via resolver.
    /// </summary>
    private static void EmitEmbeddedEntityBody(
        CodeWriter w, string varName, string relArray,
        EmbeddedEntityMetadata embedded, string targetFqn)
    {
        var classesArray = StringArrayLiteral(embedded.TargetClasses);

        // Access the Reference property (EmbeddedEntity<THto> has public Reference)
        w.Line($"var reference = ((RESTyard.AspNetCore.Hypermedia.EmbeddedEntity<{targetFqn}>){varName}).Reference;");

        w.Line("if (reference.IsResolved())");
        using (w.Block())
        {
            // Resolved — call ToSirenEmbedded() on the instance
            w.Line($"var embedded = (({targetFqn})reference.GetInstance()!).ToSirenEmbedded(resolver, queryStringBuilder, options);");
            w.Line($"embedded.Rel = {relArray};");
            w.Line("entity.Entities.Add(embedded);");
        }

        w.Line("else");
        using (w.Block())
        {
            // Unresolved — resolve via route resolver and emit a linked sub-entity.
            // Note: HypermediaExternalObjectReference is NOT handled here because its constructor
            // throws (internal ExternalObject class lacks [HypermediaObject]). It is dead code in
            // SirenConverter too. For external links, use ExternalReference via Link.External() instead.
            w.Line("var resolvedRoute = resolver.ReferenceToRoute(reference);");
            w.Line("entity.Entities.Add(new SirenLinkedEntity");
            using (w.Block(close: "});"))
            {
                w.Line($"Rel = {relArray},");
                w.Line($"Class = {classesArray},");
                w.Line("Href = resolvedRoute.Url,");
            }
        }
    }
}
