using System;
using Microsoft.AspNetCore.Mvc;
using WebApiHypermediaExtensionsCore.Hypermedia.Actions;

namespace WebApiHypermediaExtensionsCore.WebApi.AttributedRoutes
{
    [AttributeUsage(AttributeTargets.Method, Inherited = false)]
    public class HttpPostHypermediaAction : HttpPostAttribute, IHaveRouteInfo
    {
        public Type RouteType { get; private set; }
        public Type RouteKeyProducerType { get; private set; }
        /// <summary>
        /// Indicates that this route will accept posts generated by the corresponding HypermediaAction used in HypermediaObjects.
        /// Each action in a Object must be matched by a route. No other route my have the same type. A action route must be always a subroute of an HypermediaObject.
        /// </summary>
        /// <param name="routeType">type of the HypermediaAction as used in the HypermediaObject</param>
        /// <param name="routeKeyProducerType">If the route template contains a (single) key it is required that the type of the responsible RouteKeyProducer is given.
        /// This type will be used to create a n instance of the producer and generate the key object used in a UrlHelper to determin the final URL.
        /// </param>
        public HttpPostHypermediaAction(Type routeType, Type routeKeyProducerType = null)
        {
            Init(routeType, routeKeyProducerType);
        }

        /// <summary>
        /// Indicates that this route will accept posts generated by the corresponding HypermediaAction used in HypermediaObjects.
        /// Each action in a Object must be matched by a route. No other route my have the same type. A action route must be always a subroute of an HypermediaObject.
        /// </summary>
        /// <param name="template">The route template.</param>
        /// <param name="routeType">type of the HypermediaAction as used in the HypermediaObject</param>
        /// <param name="routeKeyProducerType">If the route template contains a (single) key it is required that the type of the responsible RouteKeyProducer is given.
        /// This type will be used to create a n instance of the producer and generate the key object used in a UrlHelper to determin the final URL.
        /// </param>
        public HttpPostHypermediaAction(string template, Type routeType, Type routeKeyProducerType = null) : base(template)
        {
            Init(routeType, routeKeyProducerType);
        }

        private void Init(Type routeType, Type routeKeyProducerType)
        {
            AttributedRouteHelper.EnsureIs<HypermediaActionBase>(routeType);
            AttributedRouteHelper.EnsureIsRouteKeyProducer(routeKeyProducerType);

            var buildName = "GenericRouteName_HypermediaAction" + "_" + routeType;
            buildName = AttributedRouteHelper.EscapeRouteName(buildName);

            Name = buildName;
            RouteType = routeType;
            RouteKeyProducerType = routeKeyProducerType;
        }
    }
}