<Project>
  <PropertyGroup>
    <VersionSuffixLocal></VersionSuffixLocal>
    <!--When variable is set we are building a prerelease package-->
    <VersionSuffixLocal Condition="'$(IsPreRelease)'!='' AND  '$(IsPreRelease)'">
      $(VersionSuffix)
    </VersionSuffixLocal>
    
    <!-- Bump a component's base version deliberately when preparing its next release. -->
    <RESTyardAspNetCoreVersion>6.0.2$(VersionSuffixLocal)</RESTyardAspNetCoreVersion>
    <RESTyardClientVersion>3.1.0$(VersionSuffixLocal)</RESTyardClientVersion>
    <RESTyardGeneratorVersion>0.13.1$(VersionSuffixLocal)</RESTyardGeneratorVersion>
  </PropertyGroup>
</Project>
